"""
Medical report generation - creates structured clinical reports.
"""

import os
import json
from datetime import datetime
from typing import Dict, Any, Optional
from jinja2 import Template


class MedicalReportGenerator:
    """Generate professional medical reports from analysis results."""
    
    BRAIN_TUMOR_REPORT_TEMPLATE = """
BRAIN MRI ANALYSIS REPORT
==========================================
Date of Report: {{ report_date }}
Report ID: {{ report_id }}
==========================================

CLINICAL FINDINGS:
------------------
Tumor Detection: {{ "POSITIVE" if findings.tumor_detected else "NEGATIVE" }}
Confidence Score: {{ findings.model_confidence * 100 }}%

{% if findings.tumor_detected %}
TUMOR CHARACTERISTICS:
- Location: {{ findings.location.location }}
- Affected Area: {{ findings.affected_percentage }}% of brain volume
- Severity Level: {{ findings.severity_level }}
- Estimated Diameter: {{ findings.size_metrics.estimated_diameter_mm }} mm

SIZE METRICS:
- Area: {{ findings.size_metrics.area_mm2 }} mm²
- Area (pixels): {{ findings.size_metrics.area_pixels }}

SHAPE ANALYSIS:
- Compactness: {{ findings.shape_metrics.compactness }}
- Solidity: {{ findings.shape_metrics.solidity }}
- Eccentricity: {{ findings.shape_metrics.eccentricity }}

LOCATION DETAILS:
- Primary Location: {{ findings.location.quadrants|join(", ") }}
- Center Position (% from top-left): X: {{ findings.location.center_coordinates.x_percent }}%, Y: {{ findings.location.center_coordinates.y_percent }}%
{% endif %}

CLINICAL NOTES:
{{ findings.clinical_notes }}

RECOMMENDATIONS:
{% for rec in findings.recommendations %}
{{ loop.index }}. {{ rec }}
{% endfor %}

METHODOLOGY:
- Model: U-Net with ResNet34 encoder
- Input Size: 256x256 pixels
- Output: Segmentation mask with confidence score
- Interpretation: Values > 0.5 considered positive for tumor tissue

DISCLAIMER:
This report is generated by an AI model and should NOT be used for clinical decision-making 
without review by a qualified radiologist. Always consult with medical professionals for diagnosis 
and treatment planning.

==========================================
Report Generated By: AI Medical Imaging System v1.0
Time Generated: {{ generation_time }}
"""

    KIDNEY_STONE_REPORT_TEMPLATE = """
KIDNEY ULTRASOUND/CT ANALYSIS REPORT
==========================================
Date of Report: {{ report_date }}
Report ID: {{ report_id }}
==========================================

CLINICAL FINDINGS:
------------------
Stone Detection: {{ "POSITIVE" if findings.stone_detected else "NEGATIVE" }}
Confidence Score: {{ findings.model_confidence * 100 }}%

{% if findings.stone_detected %}
STONE CHARACTERISTICS:
- Severity Level: {{ findings.severity.level }}
- Risk Score: {{ findings.severity.risk_score }}
- Immediate Risk: {{ "YES" if findings.severity.immediate_risk else "NO" }}

SIZE ASSESSMENT:
- Size Category: {{ findings.size_analysis.size_category }}
- Estimated Size: ~{{ findings.size_analysis.estimated_size_mm }} mm

CLASSIFICATION PROBABILITIES:
- Normal: {{ findings.classification_probs.normal * 100 }}%
- Stone: {{ findings.classification_probs.stone * 100 }}%

LOCATION & COMPOSITION ANALYSIS:
- Likely Location: {{ findings.location_and_composition.likely_location }}
- Probable Composition: {{ findings.location_and_composition.composition_likely }}
- Additional Characteristics: {{ findings.location_and_composition.characteristic }}
{% endif %}

CLINICAL NOTES:
{{ findings.clinical_notes }}

RECOMMENDATIONS:
{% for rec in findings.recommendations %}
{{ loop.index }}. {{ rec }}
{% endfor %}

METHODOLOGY:
- Model: ResNet18 pre-trained on ImageNet
- Classification: Binary (Normal vs Stone)
- Input Size: 224x224 pixels
- Output: Class probabilities with confidence assessment

DISCLAIMER:
This report is generated by an AI model and should NOT be used for clinical decision-making 
without review by a qualified urologist or radiologist. Always consult with medical professionals 
for diagnosis and treatment planning.

==========================================
Report Generated By: AI Medical Imaging System v1.0
Time Generated: {{ generation_time }}
"""

    UNIFIED_REPORT_TEMPLATE = """
COMPREHENSIVE MEDICAL IMAGING ANALYSIS REPORT
==========================================
Date of Report: {{ report_date }}
Report ID: {{ report_id }}
Patient Information: Cross-Organ Analysis
==========================================

EXECUTIVE SUMMARY:
{{ summary }}

STUDY INFORMATION:
- Analysis Type: Multi-Organ Screening
- Number of Models Used: 2
- Analysis Timestamp: {{ analysis_timestamp }}
- Overall Confidence: {{ overall_confidence }}%

==========================================
PART 1: BRAIN IMAGING ANALYSIS
==========================================
Tumor Detection: {{ "POSITIVE" if brain_findings.tumor_detected else "NEGATIVE" }}
Confidence: {{ brain_findings.model_confidence * 100 }}%

{% if brain_findings.tumor_detected %}
FINDINGS:
- Severity: {{ brain_findings.severity_level }}
- Affected Area: {{ brain_findings.affected_percentage }}%
- Estimated Size: {{ brain_findings.size_metrics.estimated_diameter_mm }} mm
- Location: {{ brain_findings.location.location }}

RECOMMENDATIONS FOR BRAIN:
{% for rec in brain_findings.recommendations %}
  • {{ rec }}
{% endfor %}
{% else %}
FINDINGS: No significant abnormalities detected
RECOMMENDATIONS: Routine follow-up; maintain healthy lifestyle
{% endif %}

==========================================
PART 2: KIDNEY IMAGING ANALYSIS
==========================================
Stone Detection: {{ "POSITIVE" if kidney_findings.stone_detected else "NEGATIVE" }}
Confidence: {{ kidney_findings.model_confidence * 100 }}%

{% if kidney_findings.stone_detected %}
FINDINGS:
- Severity: {{ kidney_findings.severity.level }}
- Size Category: {{ kidney_findings.size_analysis.size_category }}
- Estimated Size: ~{{ kidney_findings.size_analysis.estimated_size_mm }} mm
- Location: {{ kidney_findings.location_and_composition.likely_location }}

RECOMMENDATIONS FOR KIDNEY:
{% for rec in kidney_findings.recommendations %}
  • {{ rec }}
{% endfor %}
{% else %}
FINDINGS: No kidney stones detected
RECOMMENDATIONS: Maintain hydration; continue preventive measures
{% endif %}

==========================================
OVERALL CLINICAL ASSESSMENT:
{{ overall_assessment }}

FOLLOW-UP PLAN:
{{ follow_up_plan }}

METHODOLOGY:
- Brain Analysis: U-Net with ResNet34 segmentation
- Kidney Analysis: ResNet18 binary classification
- Integration: Multi-model consensus approach

IMPORTANT DISCLAIMER:
This is an AI-generated analysis report meant to assist medical professionals as a 
screening tool only. This report is NOT a substitute for professional medical diagnosis 
and should always be reviewed and validated by qualified radiologists and clinicians 
before any clinical decisions are made.

==========================================
Report Generated By: AI Medical Imaging System v1.0
Time Generated: {{ generation_time }}
"""

    def __init__(self, report_id: Optional[str] = None):
        """
        Initialize report generator.
        
        Args:
            report_id: Optional custom report ID
        """
        self.report_id = report_id or self._generate_report_id()
    
    @staticmethod
    def _generate_report_id() -> str:
        """Generate unique report ID."""
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        return f"REPORT_{timestamp}"
    
    def generate_brain_report(self, findings: Dict[str, Any]) -> str:
        """
        Generate brain tumor analysis report.
        
        Args:
            findings: Brain analysis findings dictionary
        
        Returns:
            Formatted report string
        """
        template = Template(self.BRAIN_TUMOR_REPORT_TEMPLATE)
        
        return template.render(
            report_date=datetime.now().strftime("%Y-%m-%d"),
            report_id=self.report_id,
            findings=findings,
            generation_time=datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        )
    
    def generate_kidney_report(self, findings: Dict[str, Any]) -> str:
        """
        Generate kidney stone analysis report.
        
        Args:
            findings: Kidney analysis findings dictionary
        
        Returns:
            Formatted report string
        """
        template = Template(self.KIDNEY_STONE_REPORT_TEMPLATE)
        
        return template.render(
            report_date=datetime.now().strftime("%Y-%m-%d"),
            report_id=self.report_id,
            findings=findings,
            generation_time=datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        )
    
    def generate_unified_report(self, 
                               brain_findings: Dict[str, Any],
                               kidney_findings: Dict[str, Any],
                               images_analyzed: int = 2) -> str:
        """
        Generate unified multi-organ analysis report.
        
        Args:
            brain_findings: Brain analysis findings
            kidney_findings: Kidney analysis findings
            images_analyzed: Number of images analyzed
        
        Returns:
            Formatted unified report
        """
        # Generate dynamic summary and assessment
        summary = self._generate_unified_summary(brain_findings, kidney_findings)
        overall_assessment = self._generate_overall_assessment(brain_findings, kidney_findings)
        follow_up_plan = self._generate_follow_up_plan(brain_findings, kidney_findings)
        overall_confidence = self._calculate_overall_confidence(brain_findings, kidney_findings)
        
        template = Template(self.UNIFIED_REPORT_TEMPLATE)
        
        return template.render(
            report_date=datetime.now().strftime("%Y-%m-%d"),
            report_id=self.report_id,
            summary=summary,
            analysis_timestamp=datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
            overall_confidence=overall_confidence,
            brain_findings=brain_findings,
            kidney_findings=kidney_findings,
            overall_assessment=overall_assessment,
            follow_up_plan=follow_up_plan,
            generation_time=datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        )
    
    @staticmethod
    def _generate_unified_summary(brain_findings: Dict, kidney_findings: Dict) -> str:
        """Generate executive summary."""
        brain_status = "brain abnormality detected" if brain_findings.get("tumor_detected") else "normal brain imaging"
        kidney_status = "kidney stone detected" if kidney_findings.get("stone_detected") else "normal kidney imaging"
        
        return f"Multi-organ screening showing {brain_status} and {kidney_status}."
    
    @staticmethod
    def _generate_overall_assessment(brain_findings: Dict, kidney_findings: Dict) -> str:
        """Generate overall clinical assessment."""
        assessments = []
        
        if brain_findings.get("tumor_detected"):
            severity = brain_findings.get("severity_level", "Unknown")
            assessments.append(f"Brain imaging shows {severity.lower()} tumor with {brain_findings.get('affected_percentage', 0):.1f}% involvement.")
        else:
            assessments.append("Brain imaging is within normal limits.")
        
        if kidney_findings.get("stone_detected"):
            severity = kidney_findings.get("severity", {}).get("level", "Unknown")
            assessments.append(f"Kidney imaging reveals {severity.lower()} stone with elevated clinical significance.")
        else:
            assessments.append("Kidney imaging shows no evidence of stone disease.")
        
        return " ".join(assessments)
    
    @staticmethod
    def _generate_follow_up_plan(brain_findings: Dict, kidney_findings: Dict) -> str:
        """Generate follow-up recommendations."""
        plan = []
        
        if brain_findings.get("tumor_detected"):
            severity = brain_findings.get("severity_level", "")
            if severity in ["Critical", "Large"]:
                plan.append("Brain: Urgent specialist consultation and advanced imaging within 48-72 hours")
            elif severity == "Moderate":
                plan.append("Brain: Specialist evaluation and repeat MRI in 1-2 months")
            else:
                plan.append("Brain: Follow-up MRI in 3 months")
        else:
            plan.append("Brain: Continue routine screening as per guidelines")
        
        if kidney_findings.get("stone_detected"):
            risk = kidney_findings.get("severity", {}).get("risk_score", 0)
            if risk > 0.7:
                plan.append("Kidney: Urgent urology consultation with imaging confirmation")
            elif risk > 0.4:
                plan.append("Kidney: Schedule urology appointment within 1-2 weeks")
            else:
                plan.append("Kidney: Routine urology follow-up with conservative management")
        else:
            plan.append("Kidney: Continue preventive hydration and dietary measures")
        
        return " | ".join(plan)
    
    @staticmethod
    def _calculate_overall_confidence(brain_findings: Dict, kidney_findings: Dict) -> float:
        """Calculate overall system confidence."""
        brain_conf = brain_findings.get("model_confidence", 0.5)
        kidney_conf = kidney_findings.get("model_confidence", 0.5)
        
        # Average of both models
        overall = (brain_conf + kidney_conf) / 2 * 100
        return round(overall, 1)
    
    def save_report(self, report_text: str, output_dir: str, 
                   report_type: str = "brain") -> str:
        """
        Save report to file.
        
        Args:
            report_text: Report content
            output_dir: Output directory
            report_type: "brain", "kidney", or "unified"
        
        Returns:
            Path to saved report
        """
        os.makedirs(output_dir, exist_ok=True)
        
        filename = f"{self.report_id}_{report_type}_report.txt"
        filepath = os.path.join(output_dir, filename)
        
        with open(filepath, "w") as f:
            f.write(report_text)
        
        return filepath
    
    def save_report_json(self, findings: Dict[str, Any], output_dir: str,
                        report_type: str = "brain") -> str:
        """
        Save report as JSON for programmatic access.
        
        Args:
            findings: Findings dictionary
            output_dir: Output directory
            report_type: "brain", "kidney", or "unified"
        
        Returns:
            Path to saved JSON report
        """
        os.makedirs(output_dir, exist_ok=True)
        
        report_data = {
            "report_id": self.report_id,
            "report_type": report_type,
            "generated_at": datetime.now().isoformat(),
            "findings": findings,
        }
        
        filename = f"{self.report_id}_{report_type}_report.json"
        filepath = os.path.join(output_dir, filename)
        
        with open(filepath, "w") as f:
            json.dump(report_data, f, indent=2)
        
        return filepath
